"""Add ConversationParticipant join table

Revision ID: 0e46e97355c9
Revises: 19314264d488
Create Date: 2026-10-06 18:31:26.385633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e46e97355c9'
down_revision: Union[str, None] = '19314264d488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uix_conversation_participant')
    )

    # Data migration
    op.execute(
        """
        INSERT INTO conversation_participants (conversation_id, user_id, joined_at)
        SELECT id, user1_id, created_at FROM conversations
        """
    )
    op.execute(
        """
        INSERT INTO conversation_participants (conversation_id, user_id, joined_at)
        SELECT id, user2_id, created_at FROM conversations
        """
    )

    op.drop_index('ix_conversations_user1_id', table_name='conversations')
    op.drop_index('ix_conversations_user2_id', table_name='conversations')
    op.drop_constraint('uix_conversation_users', 'conversations', type_='unique')
    op.drop_constraint('conversations_user1_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_user2_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'user1_id')
    op.drop_column('conversations', 'user2_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('conversations_user2_id_fkey', 'conversations', 'users', ['user2_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversations_user1_id_fkey', 'conversations', 'users', ['user1_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uix_conversation_users', 'conversations', ['user1_id', 'user2_id'])
    op.create_index('ix_conversations_user2_id', 'conversations', ['user2_id'], unique=False)
    op.create_index('ix_conversations_user1_id', 'conversations', ['user1_id'], unique=False)
    op.drop_table('conversation_participants')
    # ### end Alembic commands ###
