"""Add audio metadata to Message

Revision ID: 19314264d488
Revises: 96c6f4648009
Create Date: 2026-10-05 15:33:25.526564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19314264d488'
down_revision: Union[str, None] = '96c6f4648009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audio_url', sa.String(length=1000), nullable=True))
    op.add_column('messages', sa.Column('audio_duration_ms', sa.Integer(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'audio_duration_ms')
    op.drop_column('messages', 'audio_url')
    # ### end Alembic commands ###
