"""Add client_msg_id for idempotency

Revision ID: 96c6f4648009
Revises: 4aa0e0803c12
Create Date: 2026-10-05 10:52:18.408896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c6f4648009'
down_revision: Union[str, None] = '4aa0e0803c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('client_msg_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_messages_client_msg_id'), 'messages', ['client_msg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_client_msg_id'), table_name='messages')
    op.drop_column('messages', 'client_msg_id')
    # ### end Alembic commands ###
